### PR TITLE
This PR fixes error in pod exec through cient-go api

### PR DESCRIPTION
**Pull request by a4abhishek**
fixes error in pod exec through cient-go api
Changes committed:
	modified:   utils/k8s/k8s.go

Signed-off-by: Abhishek Kashyap <abhishek.kashyap@mayadata.io>

### CODE REVIEW

**Comment by a4abhishek** [comment]
Used following example to test
```
package main

import (
	"fmt"

	"github.com/openebs/CITF"
)

func main() {
	citfInstance, err := citf.NewCITF(".")
	if err != nil {
		panic(err)
	}

	output, _, err := citfInstance.K8S.ExecToPodThroughAPI("pwd", "kube-addon-manager-genesis", "kube-system", nil)
	if err != nil {
		panic(err)
	}

	fmt.Println("Output:", output)
}

```

**Comment by satyamz** [comment]
Excellent @a4abhishek  :1st_place_medal:

**Comment by a4abhishek** [comment]
Just found-out that it will fail for a pod which has more than one container. I shall fix it.

**Comment by a4abhishek** [comment]
Resolved in https://github.com/openebs/CITF/pull/16

**Pull request merged**
